apiVersion: networking.istio.io/v1aplha3
kind: virtualService
metadata: 
  name: httpbin
spec: 
  hosts:
    - httpbin
  http: 
  - route:
    - destination: 
        host: httpbin
        subset: v1
      weight: 100